/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dewni;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author irusha
 */
public class Student_chart extends javax.swing.JFrame {

    /**
     * Creates new form Course_chart
     */
    
    ResultSet rs;
    PreparedStatement ps;
    Statement st;
    
     DBconnect dbc = new DBconnect();
     
      int c1;// = Integer.parseInt(txt_1.getText());
                int c2;//= Integer.parseInt(txt_2.getText());
                int c3;// = Integer.parseInt(txt_3.getText());
                int c4;// = Integer.parseInt(txt_4.getText());
                int c5;// = Integer.parseInt(txt_5.getText());
                int c6;// = Integer.parseInt(txt_6.getText());
                int c7;// = Integer.parseInt(txt_7.getText());
                int c8;// = Integer.parseInt(txt_8.getText());
                int c9;// = Integer.parseInt(txt_9.getText());
                int c10;// = Integer.parseInt(txt_10.getText());
    public Student_chart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        txt_2 = new javax.swing.JTextField();
        txt_3 = new javax.swing.JTextField();
        txt_4 = new javax.swing.JTextField();
        txt_5 = new javax.swing.JTextField();
        txt_6 = new javax.swing.JTextField();
        txt_7 = new javax.swing.JTextField();
        txt_8 = new javax.swing.JTextField();
        txt_9 = new javax.swing.JTextField();
        txt_10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("c10");

        txt_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(12, 173, 183));
        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel4)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel6)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel7)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(txt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(905, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered

        jButton2.setBackground(new java.awt.Color(5, 150, 160));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited

        jButton2.setBackground(new java.awt.Color(12, 173, 183));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

               
                
               /* DefaultCategoryDataset  dataset = new DefaultCategoryDataset();
                dataset.setValue(c1, "", "c1");
                dataset.setValue(c2, "", "c2");
                dataset.setValue(c3, "", "c3");
                dataset.setValue(c4, "", "c4");
                dataset.setValue(c5, "", "c5");
                dataset.setValue(c6, "", "c6");
                dataset.setValue(c7, "", "c7");
                dataset.setValue(c8, "", "c8");
                dataset.setValue(c9, "", "c9");
                dataset.setValue(c10, "", "c10");
                         
                      
                JFreeChart chart = ChartFactory.createBarChart("Student View", "", "", dataset, PlotOrientation.VERTICAL,false,false,false);
                CategoryPlot catPlot = chart.getCate5goryPlot();
                catPlot.setRangeGridlinePaint(Color.BLACK);

                ChartPanel chartPanel = new ChartPanel(chart);
                panel.removeAll();
                panel.add(chartPanel, BorderLayout.CENTER);
                panel.validate();*/
               
               String q1 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '1'";
               String q2 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '2'";
               String q3 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '3'";          
               String q4 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '4'";
               String q5 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '5'";
               String q6 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '6'";
               String q7 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '7'";
               String q8 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '8'";
               String q9 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '9'";
               String q10 = "SELECT COUNT(courseID) as ccount FROM StudentDetails where courseID = '10'";
               
               try{
                   
                   ps = dbc.con.prepareStatement(q1);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c1 = rs.getInt("ccount");
                       System.out.println(c1);
                       txt_1.setText(Integer.toString(c1));
                   }
                   
                   ps = dbc.con.prepareStatement(q2);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c2 = rs.getInt("ccount");
                       System.out.println(c2);
                       txt_2.setText(Integer.toString(c2));
                   }
                   
                   
                   ps = dbc.con.prepareStatement(q3);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c3 = rs.getInt("ccount");
                       System.out.println(c3);
                       txt_3.setText(Integer.toString(c3));
                   }
                   
                   
                   ps = dbc.con.prepareStatement(q4);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c4 = rs.getInt("ccount");
                       System.out.println(c4);
                       txt_4.setText(Integer.toString(c4));
                   }
                   
                   ps = dbc.con.prepareStatement(q5);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c5 = rs.getInt("ccount");
                       System.out.println(c5);
                       txt_5.setText(Integer.toString(c5));
                   }
                   
                   
                   ps = dbc.con.prepareStatement(q6);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c6 = rs.getInt("ccount");
                       System.out.println(c6);
                       txt_6.setText(Integer.toString(c6));
                   }
                   
                   ps = dbc.con.prepareStatement(q7);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c7 = rs.getInt("ccount");
                       System.out.println(c7);
                       txt_7.setText(Integer.toString(c7));
                   }
                   
                   ps = dbc.con.prepareStatement(q8);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c8 = rs.getInt("ccount");
                       System.out.println(c8);
                       txt_8.setText(Integer.toString(c8));
                   }
                   
                   ps = dbc.con.prepareStatement(q9);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c9 = rs.getInt("ccount");
                       System.out.println(c9);
                       txt_9.setText(Integer.toString(c9));
                   }
                   
                   ps = dbc.con.prepareStatement(q10);
                   this.rs = this.ps.executeQuery();
                   
                   while(rs.next())
                   {
                       c10 = rs.getInt("ccount");
                       System.out.println(c10);
                       txt_10.setText(Integer.toString(c10));
                   }
                   
                   DefaultCategoryDataset  dataset = new DefaultCategoryDataset();
                dataset.setValue(c1, "", "c1");
                dataset.setValue(c2, "", "c2");
                dataset.setValue(c3, "", "c3");
                dataset.setValue(c4, "", "c4");
                dataset.setValue(c5, "", "c5");
                dataset.setValue(c6, "", "c6");
                dataset.setValue(c7, "", "c7");
                dataset.setValue(c8, "", "c8");
                dataset.setValue(c9, "", "c9");
                dataset.setValue(c10, "", "c10");
                         
                      
                JFreeChart chart = ChartFactory.createBarChart("Student View", "", "", dataset, PlotOrientation.VERTICAL,false,false,false);
                CategoryPlot catPlot = chart.getCategoryPlot();
                catPlot.setRangeGridlinePaint(Color.BLACK);

                ChartPanel chartPanel = new ChartPanel(chart);
                panel.removeAll();
                panel.add(chartPanel, BorderLayout.CENTER);
                panel.validate();
                   
                   
                   
               }catch(Exception e){}
               
               
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */   
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_chart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_10;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_6;
    private javax.swing.JTextField txt_7;
    private javax.swing.JTextField txt_8;
    private javax.swing.JTextField txt_9;
    // End of variables declaration//GEN-END:variables
}
