/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ishani;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author User
 */
public class cutomizeBridalPack extends javax.swing.JFrame {
        
     PreparedStatement pst;                                      //variable for executing dynamic query
     ResultSet rs;                                                   //variable for executing query
    Statement st;  
    GetDBConnection dbc = new GetDBConnection();                    //Connect to the database  
    customeizePackBill cusBiil = new customeizePackBill () ;
    DefaultTableModel model;
    /**
     * Creates new form cutomizeBridalPack
     */
    public cutomizeBridalPack() {
        initComponents();
          packidAutoGenerate();
         idAutoGenerate();
    }
        
        private int packidAutoGenerate()
    {
        String queryid = "SELECT MAX(PackId) FROM costomizepackages";
        int nextpackid;
        Integer packid;
        

        try {
            pst = dbc.con.prepareStatement(queryid);
            rs = this.pst.executeQuery();

            while (rs.next()) {
                nextpackid = rs.getInt(1);
                
                if(nextpackid>4)
                {
                    packid = nextpackid+1;
                    return packid;
                }
                
                else
                {
                 packid = 5;
                 return packid;
                }
                
            }

        } 
        catch (SQLException err) 
        {
            JOptionPane.showMessageDialog(this, err);
        }       
        return 0;
        
    }
          
        private int idAutoGenerate()
    {
        String queryid = "SELECT MAX(app_id) FROM appointment";
        int nextappid;

        try {
            pst = dbc.con.prepareStatement(queryid);
            rs = this.pst.executeQuery();

            while (rs.next()) {
                nextappid = rs.getInt(1);
                Integer appid = nextappid+1;
                return appid;
               
            }

        } 
        catch (SQLException err) 
        {
            JOptionPane.showMessageDialog(this, err);
        }       
        return 0;
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        submit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fnamestar = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        phoneredlab = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        packagetxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customizepackTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        totalPricejlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        carttable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 20));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 650));
        jPanel1.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Default Bridal Packages");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 60, 210, 20);

        jPanel2.setBackground(new java.awt.Color(52, 53, 57));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Package");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 100, 100, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Last Name");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(420, 20, 100, 30);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Phone num");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 60, 100, 20);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        submit.setBackground(new java.awt.Color(0, 102, 102));
        submit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("    Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        jPanel4.add(submit);
        submit.setBounds(0, 0, 90, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(780, 100, 90, 30);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("First Name");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 20, 80, 20);

        fnamestar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fnamestar.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(fnamestar);
        fnamestar.setBounds(340, 10, 60, 30);

        fnametxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fnametxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fnametxtMouseExited(evt);
            }
        });
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        fnametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnametxtKeyReleased(evt);
            }
        });
        jPanel2.add(fnametxt);
        fnametxt.setBounds(150, 10, 230, 30);

        lnametxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(lnametxt);
        lnametxt.setBounds(530, 10, 230, 30);

        phoneredlab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phoneredlab.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(phoneredlab);
        phoneredlab.setBounds(340, 50, 50, 30);

        phonetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phonetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phonetxtMouseExited(evt);
            }
        });
        phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetxtActionPerformed(evt);
            }
        });
        jPanel2.add(phonetxt);
        phonetxt.setBounds(150, 50, 230, 30);

        emailtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel2.add(emailtxt);
        emailtxt.setBounds(530, 60, 230, 30);

        packagetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        packagetxt.setEnabled(false);
        packagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packagetxtActionPerformed(evt);
            }
        });
        jPanel2.add(packagetxt);
        packagetxt.setBounds(150, 90, 230, 30);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Address");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(420, 70, 100, 20);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setBackground(new java.awt.Color(0, 204, 204));
        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("     Clear");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(900, 100, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 510, 1030, 140);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Feedback");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(310, 60, 100, 20);

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Home");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 60, 60, 20);

        jPanel3.setBackground(new java.awt.Color(52, 53, 57));
        jPanel3.setLayout(null);

        jLabel27.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("X");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel27);
        jLabel27.setBounds(970, 10, 30, 24);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 1020, 40);

        customizepackTable.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        customizepackTable.setForeground(new java.awt.Color(52, 53, 57));
        customizepackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bridal Services", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        customizepackTable.setGridColor(new java.awt.Color(0, 153, 153));
        customizepackTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customizepackTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customizepackTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 400, 210);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel1);
        jLabel1.setBounds(30, 0, 50, 20);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(660, 440, 90, 20);

        jPanel7.setBackground(new java.awt.Color(52, 53, 57));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        totalPricejlbl.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        totalPricejlbl.setForeground(new java.awt.Color(255, 255, 255));
        totalPricejlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalPricejlblMouseClicked(evt);
            }
        });
        jPanel7.add(totalPricejlbl);
        totalPricejlbl.setBounds(20, 0, 130, 20);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(830, 440, 160, 20);

        jScrollPane2.setForeground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        carttable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        carttable.setForeground(new java.awt.Color(51, 51, 51));
        carttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bridal Services"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(carttable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(690, 170, 270, 200);

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("    Add To Cart");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel4);
        jLabel4.setBounds(0, 0, 100, 20);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(490, 250, 100, 20);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel3);
        jLabel3.setBounds(30, 0, 50, 20);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(660, 440, 110, 20);

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("   Remove");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel5);
        jLabel5.setBounds(0, 0, 80, 16);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(790, 380, 80, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/customizebag.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1040, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        // SignIn signin = new SignIn();           //create sign in pop up box object
        // signin.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        BridalPack bridalpack = new BridalPack();
        bridalpack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        DefaultBridalPack defpack = new DefaultBridalPack () ;
        defpack.setVisible(true);
        this.dispose();
               
    }//GEN-LAST:event_jLabel11MouseClicked

    private void packagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packagetxtActionPerformed

    private void phonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetxtActionPerformed

    private void lnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametxtActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        
        //JOptionPane.showMessageDialog(null, "ohh");
        
        packidAutoGenerate();
        
        String fname=fnametxt.getText();
        String lname=lnametxt.getText();
        Integer phone = Integer.parseInt(phonetxt.getText());
        String email=emailtxt.getText();
        int pack= (packidAutoGenerate());
        int app= (idAutoGenerate());
      
        packagetxt.setText(Integer.toString(pack));
        
        
    if((phonetxt.getText().length()== 0)  )
        {
             JOptionPane.showMessageDialog(this, "invalid phone number");
              phoneredlab.setText("**");
               
               
               return;
            
             
        }
        
        
        else if((phonetxt.getText().length() >10)  )
        {
             JOptionPane.showMessageDialog(this, "invalid phone number");
              phoneredlab.setText("**");
               
               
               return;
          
        }
        
         else if((phonetxt.getText().length() <10)  )
        {
             JOptionPane.showMessageDialog(this, "invalid phone number");
              phoneredlab.setText("**");
               
               
               return;
            
             
        }
     
         else if(fnametxt.getText().length()== 0)
        {    
            phoneredlab.setText("");
             JOptionPane.showMessageDialog(this, "enter your first name");
             fnamestar.setText("**");
             
               return;
             
        }
           
      else
        {
           
      
        
        try {
                                            
               
              
             DefaultTableModel model = (DefaultTableModel) customizepackTable.getModel();
             DefaultTableModel cart = (DefaultTableModel) carttable.getModel();
  
                
            Double total = Double.parseDouble(totalPricejlbl.getText());

            String query1 = "insert into customer (fname,lname,phone,address) values('" + fname + "','" + lname + "','" + phone + "','" + email + "')";
            pst = dbc.con.prepareStatement(query1);
            pst.execute();
           
            
            String query2 = "insert into appointment(phone,app_id,price) values('" + phone + "','" + app + "','" + total + "')";
            pst = dbc.con.prepareStatement(query2);
            pst.execute();

           
                   int numofrow =cart.getRowCount();
                  
                   
                   for(int i=0;i<numofrow;i++)
           {
            
          
                 String bservices = cart.getValueAt(i, 0).toString();
                 String query3=" SELECT Bservices ,BservicesId  FROM BridalServices where Bservices ='"+bservices +"'  ";
                 pst = dbc.con.prepareStatement(query3);
                 this.rs = this.pst.executeQuery();
               
                 while(rs.next()){
                 int bservicesID =rs.getInt("BservicesId");
                
                 
                  String query4 = "insert into costomizepackages(PackId,phone,BservicesId,app_id) values('"+  pack +"','"+ phone +"','"+bservicesID+"','"+  app +"')";
                 pst = dbc.con.prepareStatement(query4);
                     
                pst.execute();
               
                 }
             }
                  
                
                
        }
              
              
             
          
        
        catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

        
       
           }
        
        fnametxt.setText("");
        lnametxt.setText("");
        phonetxt.setText("");
        emailtxt.setText("");
        packagetxt.setText("");
        totalPricejlbl.setText("");
        
        cusBiil.setVisible(true);
        

    }//GEN-LAST:event_submitMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
  

        fnametxt.setText("");
        lnametxt.setText("");
        phonetxt.setText("");
        emailtxt.setText("");
        packagetxt.setText("");

    }//GEN-LAST:event_jPanel4MouseClicked

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    /*    
        DefaultTableModel model = (DefaultTableModel) customizepackTable.getModel();
        DefaultTableModel cart = (DefaultTableModel) carttable.getModel();

        fnametxt.setText("");
        lnametxt.setText("");
        phonetxt.setText("");
        emailtxt.setText("");
        packagetxt.setText("");
        totalPricejlbl.setText("0.0");
        
        cart.setRowCount(0);*/
        
          cutomizeBridalPack cusbridalpack = new cutomizeBridalPack ();
           cusbridalpack.setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_jLabel13MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      String query1 = "";
      query1=" SELECT Bservices , Price FROM BridalServices ";
      
              
        try{
            
           DefaultTableModel model = (DefaultTableModel) customizepackTable.getModel();
            
            pst = dbc.con.prepareStatement(query1);
            this.rs = this.pst.executeQuery();
            //JOptionPane.showMessageDialog(this, "query right");
            
            while(rs.next())
            {              
                String BridalServ = rs.getString("Bservices");
               
                Double price = rs.getDouble("Price");
               
                model.addRow(new Object[]{BridalServ, price });        
            }
                

            
            
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(null, "Error: " + err, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        String query1 = "";
       
        
           DefaultTableModel model = (DefaultTableModel) customizepackTable.getModel();
           DefaultTableModel cart = (DefaultTableModel) carttable.getModel();
           
          double total=0;
           int numofrow =cart.getRowCount();
        
           System.out.println(numofrow);
           
           
           for(int i=0;i<numofrow;i++)
           {
            
             try{
                 String bservices = cart.getValueAt(i, 0).toString();
                 query1=" SELECT Bservices , Price FROM BridalServices where Bservices ='"+bservices +"'  ";
                 pst = dbc.con.prepareStatement(query1);
                 this.rs = this.pst.executeQuery();
                  
                 while(rs.next()){
                 Double price=rs.getDouble("price");
                 total=(total+price)*0.95;
                 
                 }
             }
             catch(Exception e){}
          
           }
           totalPricejlbl.setText(Double.toString(total));
           
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void totalPricejlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalPricejlblMouseClicked
           
        
    }//GEN-LAST:event_totalPricejlblMouseClicked

    private void customizepackTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customizepackTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) customizepackTable.getModel();
         
        
    }//GEN-LAST:event_customizepackTableMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        DefaultTableModel model = (DefaultTableModel) customizepackTable.getModel();
           DefaultTableModel cart = (DefaultTableModel) carttable.getModel();
         // double total=0;
           int row =customizepackTable.getSelectedRow();
           System.out.println(row);
           
           String Bridalservice= customizepackTable.getValueAt(row, 0).toString();  
            
           String prize = customizepackTable.getValueAt(row, 1).toString();
            
           Double price=Double.parseDouble(prize);
            
           cart.addRow(new Object[]{Bridalservice});
           model.removeRow(row);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      
        DefaultTableModel cart = (DefaultTableModel) carttable.getModel();
        DefaultTableModel model = (DefaultTableModel) customizepackTable.getModel();
        int row =carttable.getSelectedRow();
        String Bridalservice= cart.getValueAt(row, 0).toString();
        
         try{
                 String bservices = cart.getValueAt(row, 0).toString();
                 String query1=" SELECT Bservices , Price FROM BridalServices where Bservices ='"+Bridalservice +"'  ";
                 pst = dbc.con.prepareStatement(query1);
                 this.rs = this.pst.executeQuery();
                  
                 while(rs.next()){
                 Double price=rs.getDouble("price");
                 model.addRow(new Object[]{Bridalservice,price});
                 
                 }
             }
             catch(Exception e){}
          
        
        cart.removeRow(row);
        totalPricejlbl.setText("0.0");
        
      
        
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void fnametxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnametxtMouseExited
      
        
        
    }//GEN-LAST:event_fnametxtMouseExited

    private void fnametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnametxtKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fnametxtKeyReleased

    private void phonetxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonetxtMouseExited
       
         
    }//GEN-LAST:event_phonetxtMouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       
         Feedback fd=new Feedback();
         fd.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
      
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cutomizeBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cutomizeBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cutomizeBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cutomizeBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cutomizeBridalPack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carttable;
    private javax.swing.JTable customizepackTable;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel fnamestar;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JTextField packagetxt;
    private javax.swing.JLabel phoneredlab;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel totalPricejlbl;
    // End of variables declaration//GEN-END:variables
}
