/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ishani;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import javax.swing.DefaultListModel;


/**
 *
 * @author User
 */
public class DefaultBridalPack extends javax.swing.JFrame {

    
    ResultSet rs;
    PreparedStatement pst;  
    Statement st;  
    
    
    GetDBConnection dbc = new GetDBConnection(); //connect to database
    
    DefaultListModel model;
    /**
     * Creates new form DefaultBridalPack
     */
    public DefaultBridalPack() {
        initComponents();
        idAutoGenerate();
    }
        
        private int idAutoGenerate()
    {
        String queryid = "SELECT MAX(app_id) FROM appointment";
        int nextappid;

        try {
            pst = dbc.con.prepareStatement(queryid);
            rs = this.pst.executeQuery();

            while (rs.next()) {
                nextappid = rs.getInt(1);
                Integer appid = nextappid+1;
                return appid;
               
            }

        } 
        catch (SQLException err) 
        {
            JOptionPane.showMessageDialog(this, err);
        }       
        return 0;
        
    }
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        packagetxt = new javax.swing.JTextField();
        phoneredlab = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        fnamestar = new javax.swing.JLabel();
        lnametxt = new javax.swing.JTextField();
        fnametxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        silverlist = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        diamondlist = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        platinumlist = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        goldlist = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        buyplatinum = new javax.swing.JLabel();
        buygold = new javax.swing.JLabel();
        buysilver = new javax.swing.JLabel();
        buydiamond = new javax.swing.JLabel();
        val4 = new javax.swing.JLabel();
        val1 = new javax.swing.JLabel();
        val2 = new javax.swing.JLabel();
        val3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 20));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 650));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Home");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 60, 60, 20);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customize Bridal Packages");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 60, 210, 20);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("FeedBack");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(310, 60, 100, 20);

        jPanel2.setBackground(new java.awt.Color(52, 53, 57));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Package");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(430, 60, 100, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Last Name");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 60, 100, 30);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Phone num");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 110, 100, 20);

        packagetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        packagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packagetxtActionPerformed(evt);
            }
        });
        jPanel2.add(packagetxt);
        packagetxt.setBounds(540, 50, 230, 30);

        phoneredlab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phoneredlab.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(phoneredlab);
        phoneredlab.setBounds(340, 100, 40, 30);

        phonetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetxtActionPerformed(evt);
            }
        });
        phonetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phonetxtKeyReleased(evt);
            }
        });
        jPanel2.add(phonetxt);
        phonetxt.setBounds(150, 100, 230, 30);

        fnamestar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fnamestar.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(fnamestar);
        fnamestar.setBounds(340, 20, 60, 30);

        lnametxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(lnametxt);
        lnametxt.setBounds(150, 60, 230, 30);

        fnametxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        jPanel2.add(fnametxt);
        fnametxt.setBounds(150, 20, 230, 30);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel16.setBackground(new java.awt.Color(0, 102, 102));
        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("     Submit");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16);
        jLabel16.setBounds(40, 0, 90, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(830, 60, 90, 30);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel17.setBackground(new java.awt.Color(0, 102, 102));
        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("     Submit");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel17);
        jLabel17.setBounds(40, 0, 90, 30);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(830, 60, 90, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(790, 30, 90, 30);

        jLabel15.setBackground(new java.awt.Color(0, 102, 102));
        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("     Submit");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel15);
        jLabel15.setBounds(0, 0, 90, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(790, 90, 90, 30);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("First Name");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 20, 80, 20);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Address");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(430, 20, 100, 20);

        emailtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        jPanel2.add(emailtxt);
        emailtxt.setBounds(540, 10, 230, 30);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("     Clear");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel9);
        jLabel9.setBounds(0, 0, 90, 30);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(920, 90, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 510, 1020, 140);

        silverlist.setBackground(new java.awt.Color(0, 153, 153));
        silverlist.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jScrollPane1.setViewportView(silverlist);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(790, 220, 200, 170);

        diamondlist.setBackground(new java.awt.Color(0, 153, 153));
        diamondlist.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jScrollPane2.setViewportView(diamondlist);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 220, 230, 170);

        platinumlist.setBackground(new java.awt.Color(0, 153, 153));
        platinumlist.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jScrollPane3.setViewportView(platinumlist);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(300, 220, 210, 170);

        jScrollPane4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N

        goldlist.setBackground(new java.awt.Color(0, 153, 153));
        goldlist.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jScrollPane4.setViewportView(goldlist);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(540, 220, 210, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/silver.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(790, 170, 190, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/platinumy.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 170, 190, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/diamond.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 170, 190, 40);

        jPanel3.setBackground(new java.awt.Color(52, 53, 57));
        jPanel3.setLayout(null);

        jLabel27.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("X");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel27);
        jLabel27.setBounds(980, 10, 30, 24);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 1020, 40);

        buyplatinum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/byenowpng.png"))); // NOI18N
        buyplatinum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyplatinumMouseClicked(evt);
            }
        });
        jPanel1.add(buyplatinum);
        buyplatinum.setBounds(330, 440, 140, 30);

        buygold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/byenowpng.png"))); // NOI18N
        buygold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buygoldMouseClicked(evt);
            }
        });
        jPanel1.add(buygold);
        buygold.setBounds(590, 440, 140, 30);

        buysilver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/byenowpng.png"))); // NOI18N
        buysilver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buysilverMouseClicked(evt);
            }
        });
        jPanel1.add(buysilver);
        buysilver.setBounds(830, 440, 140, 30);

        buydiamond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/byenowpng.png"))); // NOI18N
        buydiamond.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buydiamondMouseClicked(evt);
            }
        });
        jPanel1.add(buydiamond);
        buydiamond.setBounds(50, 440, 140, 30);

        val4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        val4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(val4);
        val4.setBounds(850, 400, 90, 20);

        val1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        val1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(val1);
        val1.setBounds(80, 410, 90, 20);

        val2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        val2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(val2);
        val2.setBounds(360, 400, 90, 20);

        val3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        val3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(val3);
        val3.setBounds(600, 400, 90, 20);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/gold copy.png"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(550, 170, 190, 40);

        jLabel3.setBackground(new java.awt.Color(52, 53, 57));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/defaultpac.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1020, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        // SignIn signin = new SignIn();           //create sign in pop up box object
        // signin.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void packagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packagetxtActionPerformed

    private void phonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetxtActionPerformed

    private void lnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametxtActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        BridalPack bridalpack = new BridalPack();
        bridalpack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
                packagetxt.setEnabled(false);
        
                String query1 = "";
                String query2 = "";
                String query3 = "";
                String query4 = "";
                String query5 = "";
                String query6 = "";
                String query7 = "";
                String query8 = "";
                
                query1= "SELECT * FROM diamondpack" ;
                query2= "SELECT * FROM platinumpack"; 
                query3= "SELECT * FROM goldpack"; 
                query4= "SELECT * FROM silverpack"; 
                query5= "SELECT Price FROM defaultpackage where PackId='1'"; 
                query6= "SELECT Price FROM defaultpackage where PackId='2'"; 
                query7= "SELECT Price FROM defaultpackage where PackId='3'"; 
                query8= "SELECT Price FROM defaultpackage where PackId='4'"; 
               
                
//----------------------------------------------       
            //DIAMOND PACKAGE VALUES
                
        try{
            
          
            DefaultListModel model = new DefaultListModel(); //create a new list model
            
            pst = dbc.con.prepareStatement(query1);
            this.rs = this.pst.executeQuery();
           // JOptionPane.showMessageDialog(this, "query right");
            
            while(rs.next())
            {                
                
                        String diamondList = rs.getString("Bservices"); //get the element in column "Bservices"
                        model.addElement(diamondList); //add each item to the model
            }
             diamondlist.setModel(model);
             //JOptionPane.showMessageDialog(this, "query right");
            /*rs.close();
            st.close();*/
           
   
            
            
            
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(null, "Error: " + err, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //----------------------------------------------------------------------
        
         //PLATINUM PACKAGE VALUES
            // JOptionPane.showMessageDialog(this, "query right");               
        try{
            
           // JOptionPane.showMessageDialog(this, "query right");
            DefaultListModel model = new DefaultListModel(); //create a new list model
            pst = dbc.con.prepareStatement(query2);
            this.rs = this.pst.executeQuery();
           // JOptionPane.showMessageDialog(this, "query right");
             //JOptionPane.showMessageDialog(this, "query right");
            while(rs.next())
            {                
                
                        String platinumList = rs.getString("Bservices"); //get the element in column "Bservices"
                        model.addElement(platinumList); //add each item to the model
            }
             platinumlist.setModel(model);

            //rs.close();
            //st.close();
            
            
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(null, "Error: " + err, "Error", JOptionPane.ERROR_MESSAGE);
        }
            
         //----------------------------------------------------------------------
        
          //GOLD PACKAGE VALUES
                           
        try{
            
           //JOptionPane.showMessageDialog(this, "query right");
            DefaultListModel model = new DefaultListModel(); //create a new list model
            pst = dbc.con.prepareStatement(query3);
            this.rs = this.pst.executeQuery();
           // JOptionPane.showMessageDialog(this, "query right");
            
            while(rs.next())
            {                
               // JOptionPane.showMessageDialog(this, "query right");
                       String goldList = rs.getString("Bservices"); //get the element in column "Bservices"
                        model.addElement(goldList); //add each item to the model
                        //JOptionPane.showMessageDialog(this, "query right");
            }
             goldlist.setModel(model);
            // JOptionPane.showMessageDialog(this, "query right");

            //rs.close();
            //st.close();
            
            
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(null, "Error: " + err, "Error", JOptionPane.ERROR_MESSAGE);
        }
       //----------------------------------------------------------------------
        
          //SILVER PACKAGE VALUES
                           
        try{
            
           
            DefaultListModel model = new DefaultListModel(); //create a new list model
            pst = dbc.con.prepareStatement(query2);
            this.rs = this.pst.executeQuery();
           
            
            while(rs.next())
            {                
                
                        String silverList = rs.getString("Bservices"); 
                        model.addElement(silverList); 
            }
             silverlist.setModel(model);
             
             //----------------------------------------------------------
             
             pst = dbc.con.prepareStatement(query5);
             this.rs = this.pst.executeQuery();
            
            while(rs.next())
            {                
                
                        double valu1 = rs.getDouble("price"); 
                       val1.setText(Double.toString(valu1));
            }
            
               
             pst = dbc.con.prepareStatement(query6);
             this.rs = this.pst.executeQuery();
            
            while(rs.next())
            {                
                
                        double valu2 = rs.getDouble("price"); 
                       val2.setText(Double.toString(valu2));
            }
            
               
             pst = dbc.con.prepareStatement(query7);
             this.rs = this.pst.executeQuery();
           
            while(rs.next())
            {                
                
                        double valu3 = rs.getDouble("price"); 
                       val3.setText(Double.toString(valu3));
            }
            
               
             pst = dbc.con.prepareStatement(query8);
             this.rs = this.pst.executeQuery();
           
            while(rs.next())
            {                
                
                        double valu4 = rs.getDouble("price"); 
                       val4.setText(Double.toString(valu4));
            }
             
             
             

           
            
            
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(null, "Error: " + err, "Error", JOptionPane.ERROR_MESSAGE);
        }
      
               
                
    }//GEN-LAST:event_formWindowOpened

    private void buydiamondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buydiamondMouseClicked
        // TODO add your handling code here:
        buyplatinum.setEnabled(false);
        buygold.setEnabled(false);
        buysilver.setEnabled(false);
        
        packagetxt.setText("DIAMOND");
        
        String Package = "DIAMOND";
        
        
        
    }//GEN-LAST:event_buydiamondMouseClicked

    private void buyplatinumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyplatinumMouseClicked
        // TODO add your handling code here:
        
         buydiamond.setEnabled(false);
         buygold.setEnabled(false);
        buysilver.setEnabled(false);
        
        packagetxt.setText("PLATINUM");
        
        String Package = "PLATINUM";
        
    }//GEN-LAST:event_buyplatinumMouseClicked

    private void buygoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buygoldMouseClicked
        // TODO add your handling code here:
        
        buyplatinum.setEnabled(false);
        buydiamond.setEnabled(false);
        buysilver.setEnabled(false);
        
        packagetxt.setText("GOLD");
        
        
        String Package = "GOLD";
        
        
    }//GEN-LAST:event_buygoldMouseClicked

    private void buysilverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buysilverMouseClicked
        // TODO add your handling code here:
                buyplatinum.setEnabled(false);
        buygold.setEnabled(false);
        buydiamond.setEnabled(false);
        
        packagetxt.setText("SILVER");
        
        String Package = "SILVER";
    }//GEN-LAST:event_buysilverMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
         buyplatinum.setEnabled(true);
        buygold.setEnabled(true);
        buysilver.setEnabled(true);
        buydiamond.setEnabled(true);
        
        fnametxt.setText("");
        lnametxt.setText("");
        phonetxt.setText("");
        emailtxt.setText("");
        packagetxt.setText("");
        
        
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        buyplatinum.setEnabled(true);
        buygold.setEnabled(true);
        buysilver.setEnabled(true);
        buydiamond.setEnabled(true);
        
        fnametxt.setText("");
        lnametxt.setText("");
        phonetxt.setText("");
        emailtxt.setText("");
        packagetxt.setText("");
        
       
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        
        double prise=0.00;
        
        idAutoGenerate();
        String fname=fnametxt.getText();
        String lname=lnametxt.getText();
        Integer phone = Integer.parseInt(phonetxt.getText());
        String email=emailtxt.getText();
        String pack=packagetxt.getText();
        String statuz="Default";
        
          if(packagetxt.getText().length()== 0)
        {    
             
             JOptionPane.showMessageDialog(this, "Select Package !! ");
             
             
               return;
             
        }
        
         else if((phonetxt.getText().length()== 0)  )
        {
             JOptionPane.showMessageDialog(this, "invalid phone number");
              phoneredlab.setText("**");
               
               
               return;
            
             
        }
        
        
        else if((phonetxt.getText().length() >10)  )
        {
             JOptionPane.showMessageDialog(this, "invalid phone number");
              phoneredlab.setText("**");
              phoneredlab.requestFocusInWindow(); 
               
               return;
          
        }
        
         else if((phonetxt.getText().length() < 10)  )
        {
             JOptionPane.showMessageDialog(this, "invalid phone number");
              phoneredlab.setText("**");
              phoneredlab.requestFocusInWindow(); 
               
               return;
            
             
        }
     
         else if(fnametxt.getText().length()== 0)
        {    
            phoneredlab.setText("");
             JOptionPane.showMessageDialog(this, "enter your first name");
             fnamestar.requestFocusInWindow(); 
            fnamestar.setText("**");
             
               return;
             
        }
         
         
           
      else
        {          
                    fnamestar.setText("");
        try {
           
            
            
              String query1 = "insert into customer (fname,lname,phone,address) values('" + fname + "','" + lname + "','" + phone + "','" + email + "')";
              pst = dbc.con.prepareStatement(query1);
              
              pst.execute();
        
              
               String query3 = "SELECT Price FROM defaultpackage Where PackName = '" + pack + "' ";
               pst = dbc.con.prepareStatement(query3); 
               
               this.rs = this.pst.executeQuery();
               
                  while(rs.next())
            {               
               //JOptionPane.showMessageDialog(null, "ohh");
               prise = rs.getDouble("Price");
               //JOptionPane.showMessageDialog(null, "Sucsessfull !!!");
               
            }
               
               String query2 = "insert into appointment(phone,app_id,status,price) values('"+ phone +"','"+  idAutoGenerate() +"','"+ statuz +"','"+ prise +"')";
               pst = dbc.con.prepareStatement(query2);
               pst.execute();
                JOptionPane.showMessageDialog(null, "Sucsessfull !!!");
            
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, " Error");
        }

        }
        
        
        
    
        
       fnametxt.setText("");
        lnametxt.setText("");
        phonetxt.setText("");
        emailtxt.setText("");
        packagetxt.setText("");
        
        DefaultPackBill defbill = new DefaultPackBill ();
       defbill.setVisible(true);
        
        
        
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void phonetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonetxtKeyReleased
        
         
    
        
        
    }//GEN-LAST:event_phonetxtKeyReleased

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         cutomizeBridalPack cusbridalpack = new cutomizeBridalPack ();
        cusbridalpack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
     
        Feedback fd=new Feedback();
        fd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
       
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefaultBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefaultBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefaultBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefaultBridalPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaultBridalPack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buydiamond;
    private javax.swing.JLabel buygold;
    private javax.swing.JLabel buyplatinum;
    private javax.swing.JLabel buysilver;
    private javax.swing.JList diamondlist;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel fnamestar;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JList goldlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JTextField packagetxt;
    private javax.swing.JLabel phoneredlab;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JList platinumlist;
    private javax.swing.JList silverlist;
    private javax.swing.JLabel val1;
    private javax.swing.JLabel val2;
    private javax.swing.JLabel val3;
    private javax.swing.JLabel val4;
    // End of variables declaration//GEN-END:variables
}
