/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ishani;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author User
 */
public class Feedback extends javax.swing.JFrame {

    PreparedStatement pst;                                      //variable for executing dynamic query
    ResultSet rs;                                                   //variable for executing query
    Statement st;  
    GetDBConnection dbc = new GetDBConnection(); 
    
    public Feedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private int feedidAutoGenerate()
    {
        String queryid = "SELECT MAX(feedback_id) FROM feedbacki";
        int nextfeedid;
        Integer id;
        

        try {
            pst = dbc.con.prepareStatement(queryid);
            rs = this.pst.executeQuery();

            while (rs.next()) {
                nextfeedid = rs.getInt(1);
                
                
                   id = nextfeedid+1;
                    return id;
               
                 
                
                
            }

        } 
        catch (SQLException err) 
        {
            JOptionPane.showMessageDialog(this, err);
        }       
        return 0;
        
    }
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1 = new javax.swing.ButtonGroup();
        Q2 = new javax.swing.ButtonGroup();
        Q3 = new javax.swing.ButtonGroup();
        Q4 = new javax.swing.ButtonGroup();
        Q5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Q1Answer3 = new javax.swing.JRadioButton();
        Q1Answer1 = new javax.swing.JRadioButton();
        Q1Answer2 = new javax.swing.JRadioButton();
        Q3Answer1 = new javax.swing.JRadioButton();
        Q2Answer2 = new javax.swing.JRadioButton();
        Q2Answer3 = new javax.swing.JRadioButton();
        Q2Answer4 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        Q1Answer4 = new javax.swing.JRadioButton();
        Q2Answer1 = new javax.swing.JRadioButton();
        Q3Answer3 = new javax.swing.JRadioButton();
        Q3Answer2 = new javax.swing.JRadioButton();
        Q3Answer4 = new javax.swing.JRadioButton();
        Q1Answer5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Q4Answer1 = new javax.swing.JRadioButton();
        Q4Answer3 = new javax.swing.JRadioButton();
        Q4Answer2 = new javax.swing.JRadioButton();
        Q4Answer4 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Q5Answer1 = new javax.swing.JRadioButton();
        Q5Answer3 = new javax.swing.JRadioButton();
        Q5Answer2 = new javax.swing.JRadioButton();
        Q5Answer4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 20));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 650));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Home");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 60, 60, 20);

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customize Bridal Packages");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 60, 190, 20);

        jPanel3.setBackground(new java.awt.Color(52, 53, 57));
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("FeedBack");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel14);
        jLabel14.setBounds(520, 10, 100, 20);

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Default Bridal Packages");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel18);
        jLabel18.setBounds(310, 10, 180, 20);

        jLabel27.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("X");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel27);
        jLabel27.setBounds(940, 10, 40, 24);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 1020, 40);

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setPreferredSize(new java.awt.Dimension(1024, 650));
        jPanel10.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Home");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel19);
        jLabel19.setBounds(20, 60, 60, 20);

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Customize Bridal Packages");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanel10.add(jLabel12);
        jLabel12.setBounds(100, 60, 190, 20);

        jPanel11.setBackground(new java.awt.Color(52, 53, 57));
        jPanel11.setLayout(null);

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Default Bridal Packages");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
        });
        jPanel11.add(jLabel21);
        jLabel21.setBounds(310, 10, 180, 20);

        jLabel28.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("X");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel28);
        jLabel28.setBounds(940, 10, 40, 24);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(0, 50, 1020, 40);

        jPanel13.setBackground(new java.awt.Color(52, 53, 57));
        jPanel13.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(0, 153, 153));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });
        jPanel15.setLayout(null);

        jLabel22.setBackground(new java.awt.Color(0, 102, 102));
        jLabel22.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("     Submit");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel22);
        jLabel22.setBounds(40, 0, 90, 30);

        jPanel14.add(jPanel15);
        jPanel15.setBounds(830, 60, 90, 30);

        submit.setBackground(new java.awt.Color(0, 102, 102));
        submit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("     Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        jPanel14.add(submit);
        submit.setBounds(0, 0, 90, 30);

        jPanel13.add(jPanel14);
        jPanel14.setBounds(810, 30, 90, 30);

        jPanel16.setBackground(new java.awt.Color(0, 153, 153));
        jPanel16.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(0, 102, 102));
        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No Thanks");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel16.add(jLabel10);
        jLabel10.setBounds(10, 0, 90, 30);

        jPanel13.add(jPanel16);
        jPanel16.setBounds(910, 30, 90, 30);

        jPanel17.setBackground(new java.awt.Color(0, 153, 153));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });
        jPanel17.setLayout(null);

        jPanel18.setBackground(new java.awt.Color(0, 153, 153));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });
        jPanel18.setLayout(null);

        jLabel24.setBackground(new java.awt.Color(0, 102, 102));
        jLabel24.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("     Submit");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel18.add(jLabel24);
        jLabel24.setBounds(40, 0, 90, 30);

        jPanel17.add(jPanel18);
        jPanel18.setBounds(830, 60, 90, 30);

        jPanel13.add(jPanel17);
        jPanel17.setBounds(1580, 80, 90, 30);

        jPanel10.add(jPanel13);
        jPanel13.setBounds(0, 570, 1030, 80);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Which Package Are you Selected?");
        jPanel10.add(jLabel25);
        jLabel25.setBounds(100, 100, 330, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Q1");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(40, 110, 34, 14);

        Q1Answer3.setBackground(new java.awt.Color(52, 53, 57));
        Q1.add(Q1Answer3);
        Q1Answer3.setForeground(new java.awt.Color(255, 255, 255));
        Q1Answer3.setText("Gold");
        Q1Answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1Answer3ActionPerformed(evt);
            }
        });
        jPanel10.add(Q1Answer3);
        Q1Answer3.setBounds(100, 160, 180, 20);

        Q1Answer1.setBackground(new java.awt.Color(52, 53, 57));
        Q1.add(Q1Answer1);
        Q1Answer1.setForeground(new java.awt.Color(255, 255, 255));
        Q1Answer1.setText("Diamond");
        jPanel10.add(Q1Answer1);
        Q1Answer1.setBounds(100, 130, 180, 20);

        Q1Answer2.setBackground(new java.awt.Color(52, 53, 57));
        Q1.add(Q1Answer2);
        Q1Answer2.setForeground(new java.awt.Color(255, 255, 255));
        Q1Answer2.setText("Platinum");
        jPanel10.add(Q1Answer2);
        Q1Answer2.setBounds(320, 130, 180, 20);

        Q3Answer1.setBackground(new java.awt.Color(52, 53, 57));
        Q3.add(Q3Answer1);
        Q3Answer1.setForeground(new java.awt.Color(255, 255, 255));
        Q3Answer1.setText("Strongly Agree");
        jPanel10.add(Q3Answer1);
        Q3Answer1.setBounds(100, 380, 180, 20);

        Q2Answer2.setBackground(new java.awt.Color(52, 53, 57));
        Q2.add(Q2Answer2);
        Q2Answer2.setForeground(new java.awt.Color(255, 255, 255));
        Q2Answer2.setText("Somewhat Agree");
        jPanel10.add(Q2Answer2);
        Q2Answer2.setBounds(320, 260, 180, 20);

        Q2Answer3.setBackground(new java.awt.Color(52, 53, 57));
        Q2.add(Q2Answer3);
        Q2Answer3.setForeground(new java.awt.Color(255, 255, 255));
        Q2Answer3.setText("Neither Agree or Disagree");
        jPanel10.add(Q2Answer3);
        Q2Answer3.setBounds(100, 290, 180, 20);

        Q2Answer4.setBackground(new java.awt.Color(52, 53, 57));
        Q2.add(Q2Answer4);
        Q2Answer4.setForeground(new java.awt.Color(255, 255, 255));
        Q2Answer4.setText("DisAgree");
        jPanel10.add(Q2Answer4);
        Q2Answer4.setBounds(320, 290, 180, 20);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Q3");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(40, 350, 20, 17);

        Q1Answer4.setBackground(new java.awt.Color(52, 53, 57));
        Q1.add(Q1Answer4);
        Q1Answer4.setForeground(new java.awt.Color(255, 255, 255));
        Q1Answer4.setText("Silver");
        jPanel10.add(Q1Answer4);
        Q1Answer4.setBounds(320, 160, 180, 20);

        Q2Answer1.setBackground(new java.awt.Color(52, 53, 57));
        Q2.add(Q2Answer1);
        Q2Answer1.setForeground(new java.awt.Color(255, 255, 255));
        Q2Answer1.setText("Strongly Agree");
        jPanel10.add(Q2Answer1);
        Q2Answer1.setBounds(100, 260, 180, 20);

        Q3Answer3.setBackground(new java.awt.Color(52, 53, 57));
        Q3.add(Q3Answer3);
        Q3Answer3.setForeground(new java.awt.Color(255, 255, 255));
        Q3Answer3.setText("Neither Agree or Disagree");
        jPanel10.add(Q3Answer3);
        Q3Answer3.setBounds(100, 410, 180, 20);

        Q3Answer2.setBackground(new java.awt.Color(52, 53, 57));
        Q3.add(Q3Answer2);
        Q3Answer2.setForeground(new java.awt.Color(255, 255, 255));
        Q3Answer2.setText("Somewhat Agree");
        jPanel10.add(Q3Answer2);
        Q3Answer2.setBounds(310, 380, 180, 20);

        Q3Answer4.setBackground(new java.awt.Color(52, 53, 57));
        Q3.add(Q3Answer4);
        Q3Answer4.setForeground(new java.awt.Color(255, 255, 255));
        Q3Answer4.setText("DisAgree");
        jPanel10.add(Q3Answer4);
        Q3Answer4.setBounds(310, 410, 180, 20);

        Q1Answer5.setBackground(new java.awt.Color(52, 53, 57));
        Q1.add(Q1Answer5);
        Q1Answer5.setForeground(new java.awt.Color(255, 255, 255));
        Q1Answer5.setText("Other");
        jPanel10.add(Q1Answer5);
        Q1Answer5.setBounds(100, 190, 180, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("I am very stisfied with this Youser friendly Application");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(100, 220, 370, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Packages are well Balanced");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(100, 340, 620, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Q2");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(40, 230, 20, 17);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Receptionist gave Instructions to handle system and Receptionist are Knowlagebel and professional");
        jPanel10.add(jLabel31);
        jLabel31.setBounds(100, 450, 670, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Q4");
        jPanel10.add(jLabel32);
        jLabel32.setBounds(40, 460, 20, 17);

        Q4Answer1.setBackground(new java.awt.Color(52, 53, 57));
        Q4.add(Q4Answer1);
        Q4Answer1.setForeground(new java.awt.Color(255, 255, 255));
        Q4Answer1.setText("Strongly Agree");
        jPanel10.add(Q4Answer1);
        Q4Answer1.setBounds(100, 490, 180, 20);

        Q4Answer3.setBackground(new java.awt.Color(52, 53, 57));
        Q4.add(Q4Answer3);
        Q4Answer3.setForeground(new java.awt.Color(255, 255, 255));
        Q4Answer3.setText("Neither Agree or Disagree");
        jPanel10.add(Q4Answer3);
        Q4Answer3.setBounds(100, 520, 180, 20);

        Q4Answer2.setBackground(new java.awt.Color(52, 53, 57));
        Q4.add(Q4Answer2);
        Q4Answer2.setForeground(new java.awt.Color(255, 255, 255));
        Q4Answer2.setText("Somewhat Agree");
        jPanel10.add(Q4Answer2);
        Q4Answer2.setBounds(310, 490, 180, 20);

        Q4Answer4.setBackground(new java.awt.Color(52, 53, 57));
        Q4.add(Q4Answer4);
        Q4Answer4.setForeground(new java.awt.Color(255, 255, 255));
        Q4Answer4.setText("DisAgree");
        jPanel10.add(Q4Answer4);
        Q4Answer4.setBounds(310, 520, 180, 20);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Overall, I am very Satisfy with the Hasini gunasekara salons pvt lmtd");
        jPanel10.add(jLabel33);
        jLabel33.setBounds(590, 100, 430, 40);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Q5");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(560, 110, 20, 20);

        Q5Answer1.setBackground(new java.awt.Color(52, 53, 57));
        Q5.add(Q5Answer1);
        Q5Answer1.setForeground(new java.awt.Color(255, 255, 255));
        Q5Answer1.setText("Strongly Agree");
        jPanel10.add(Q5Answer1);
        Q5Answer1.setBounds(590, 150, 180, 20);

        Q5Answer3.setBackground(new java.awt.Color(52, 53, 57));
        Q5.add(Q5Answer3);
        Q5Answer3.setForeground(new java.awt.Color(255, 255, 255));
        Q5Answer3.setText("Neither Agree or Disagree");
        jPanel10.add(Q5Answer3);
        Q5Answer3.setBounds(590, 180, 180, 20);

        Q5Answer2.setBackground(new java.awt.Color(52, 53, 57));
        Q5.add(Q5Answer2);
        Q5Answer2.setForeground(new java.awt.Color(255, 255, 255));
        Q5Answer2.setText("Somewhat Agree");
        jPanel10.add(Q5Answer2);
        Q5Answer2.setBounds(800, 150, 180, 20);

        Q5Answer4.setBackground(new java.awt.Color(52, 53, 57));
        Q5.add(Q5Answer4);
        Q5Answer4.setForeground(new java.awt.Color(255, 255, 255));
        Q5Answer4.setText("DisAgree");
        jPanel10.add(Q5Answer4);
        Q5Answer4.setBounds(800, 180, 180, 20);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(0, 0, 1024, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        BridalPack bridalpack = new BridalPack();
        bridalpack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        cutomizeBridalPack cusbridalpack = new cutomizeBridalPack ();
        cusbridalpack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
       
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        DefaultBridalPack defpack = new DefaultBridalPack () ;
        defpack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        BridalPack bridalpack = new BridalPack();
        bridalpack.setVisible(true);
        DefaultBridalPack def = new DefaultBridalPack ();
        def.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
      
        double value1=0.0;
        double value2=0.0;
        double value3=0.0;
        double value4=0.0;
        double value5=0.0;
        double total=0.0;
        
        
         if(Q1Answer1.isSelected())
         {
             value1=1;
         }
         else if(Q1Answer2.isSelected())
         {
             value1=2;
         }
         else if(Q1Answer3.isSelected())
         {
             value1=3;
         }
         else if(Q1Answer4.isSelected())
         {
             value1=4;
         }
         else if(Q1Answer5.isSelected())
         {
             value1=5;
         }
         
         
         if(Q2Answer1.isSelected())
         {
             value2=1;
         }
         else if(Q2Answer2.isSelected())
         {
             value2=0.75;
         }
         else if(Q2Answer3.isSelected())
         {
             value2=0.5;
         }
         else if(Q2Answer4.isSelected())
         {
             value2=0;
         }
         else
         {
             JOptionPane.showMessageDialog(this,"Choose ansewer to Q2 !! ");
             return;
         }
         
         
          if(Q3Answer1.isSelected())
         {
             value3=1;
         }
         else if(Q3Answer2.isSelected())
         {
             value3=0.75;
         }
         else if(Q3Answer3.isSelected())
         {
             value3=0.5;
         }
         else if(Q3Answer4.isSelected())
         {
             value3=0;
         }
           else
         {
             JOptionPane.showMessageDialog(this,"Choose ansewer to Q3 !! ");
             return;
         }
          
          
           if(Q4Answer1.isSelected())
         {
             value4=1;
         }
         else if(Q4Answer2.isSelected())
         {
             value4=0.75;
         }
         else if(Q4Answer3.isSelected())
         {
             value4=0.5;
         }
         else if(Q4Answer4.isSelected())
         {
             value4=0;
         }
             else
         {
             JOptionPane.showMessageDialog(this,"Choose ansewer to Q4 !! ");
             return;
         }
           
           
            if(Q5Answer1.isSelected())
         {
             value5=1;
         }
         else if(Q5Answer2.isSelected())
         {
             value5=0.75;
         }
         else if(Q5Answer3.isSelected())
         {
             value5=0.5;
         }
         else if(Q5Answer4.isSelected())
         {
             value5=0;
         }
              else
         {
             JOptionPane.showMessageDialog(this,"Choose ansewer to Q5 !! ");
             return;
         }
            
             total=value2+value3+value4+value5;
        
         try 
         {
            String query1 = "insert into feedbacki  values('" + feedidAutoGenerate() + "','" + value1 + "','" + value2 + "','" + value3 + "','" + value4 + "','" + value5 + "','" + total + "')";
            pst = dbc.con.prepareStatement(query1);
       
            pst.execute();
        } 
         
         catch (SQLException ex) 
         {
            Logger.getLogger(Feedback.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         JOptionPane.showMessageDialog(this, "Thank you for your feedback!!" );
            
            
       feedbackresult fdr =new feedbackresult();
       fdr.setVisible(true);
       
        
       
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_submitMouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
         DefaultBridalPack defpack = new DefaultBridalPack () ;
         defpack.setVisible(true);
        
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void Q1Answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1Answer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q1Answer3ActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel28MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Q1;
    private javax.swing.JRadioButton Q1Answer1;
    private javax.swing.JRadioButton Q1Answer2;
    private javax.swing.JRadioButton Q1Answer3;
    private javax.swing.JRadioButton Q1Answer4;
    private javax.swing.JRadioButton Q1Answer5;
    private javax.swing.ButtonGroup Q2;
    private javax.swing.JRadioButton Q2Answer1;
    private javax.swing.JRadioButton Q2Answer2;
    private javax.swing.JRadioButton Q2Answer3;
    private javax.swing.JRadioButton Q2Answer4;
    private javax.swing.ButtonGroup Q3;
    private javax.swing.JRadioButton Q3Answer1;
    private javax.swing.JRadioButton Q3Answer2;
    private javax.swing.JRadioButton Q3Answer3;
    private javax.swing.JRadioButton Q3Answer4;
    private javax.swing.ButtonGroup Q4;
    private javax.swing.JRadioButton Q4Answer1;
    private javax.swing.JRadioButton Q4Answer2;
    private javax.swing.JRadioButton Q4Answer3;
    private javax.swing.JRadioButton Q4Answer4;
    private javax.swing.ButtonGroup Q5;
    private javax.swing.JRadioButton Q5Answer1;
    private javax.swing.JRadioButton Q5Answer2;
    private javax.swing.JRadioButton Q5Answer3;
    private javax.swing.JRadioButton Q5Answer4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables
}
