/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ishani;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class feedbackresult extends javax.swing.JFrame {

       PreparedStatement pst;                                      //variable for executing dynamic query
     ResultSet rs;                                                   //variable for executing query
    Statement st;  
    GetDBConnection dbc = new GetDBConnection(); 
     int id ;
     double result;
    
    public feedbackresult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        dot1 = new javax.swing.JLabel();
        dot2 = new javax.swing.JLabel();
        dot3 = new javax.swing.JLabel();
        dot4 = new javax.swing.JLabel();
        dot5 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(31, 156, 162));
        jPanel1.setPreferredSize(new java.awt.Dimension(362, 265));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(67, 70, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Feedback Rate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 30, 30, 20));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 41, 30, 20));

        status.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Highly satisfyed");
        jPanel2.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 132, 25));

        dot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/star2.png"))); // NOI18N
        jPanel2.add(dot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 40, -1));

        dot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/star2.png"))); // NOI18N
        jPanel2.add(dot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 40, -1));

        dot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/star2.png"))); // NOI18N
        jPanel2.add(dot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 40, -1));

        dot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/star2.png"))); // NOI18N
        jPanel2.add(dot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 40, -1));

        dot5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ishani/ImagesCustom/star2.png"))); // NOI18N
        jPanel2.add(dot5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 40, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 250));

        jLabel27.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("X");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    //  this.dispose();
    }//GEN-LAST:event_formMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
       
        String q1 = "SELECT MAX(feedback_id) FROM feedbacki";
        
       
          try 
          {
            
            
            pst = dbc.con.prepareStatement(q1);
            rs = this.pst.executeQuery();
          
            while (rs.next())
            {
               id = rs.getInt(1);
               
               
            }
            
           
            String query=" SELECT result  FROM feedbacki where feedback_id='"+id+"' ";
            
            
         
            
            
            pst = dbc.con.prepareStatement(query);
            rs = this.pst.executeQuery();
           
            while (rs.next())
            {
              result= rs.getDouble(1);
               
               
            }
            
            if(result < 0.5  )
            {
                dot1.setVisible(false);
                dot2.setVisible(false);
                dot3.setVisible(false);
                dot4.setVisible(false);
                dot5.setVisible(false);
                status.setText("Not satisfied");
                
            }
            else if(result <= 1 && result >0.5 )
            {
                dot2.setVisible(false);
                dot3.setVisible(false);
                dot4.setVisible(false);
                dot5.setVisible(false);
                status.setText("some what satisfied");
            }
            
             else if(result <= 2.5 && result >1 )
            {
               
                dot3.setVisible(false);
                dot4.setVisible(false);
                dot5.setVisible(false);
                status.setText(" satisfied");
            }
            
             else if(result <= 3.0 && result >2.5 )
            {
               
                
                dot4.setVisible(false);
                dot5.setVisible(false);
                status.setText("satisfied");
            }
            
             else if(result <4.0 && result >3.0 )
            {
               
                dot5.setVisible(false);
                status.setText("Highly satisfied");
            }
            
            
            
            
            
            
            
          }
            
          catch (Exception e)
                    {
                    
                    }
        
    }//GEN-LAST:event_formWindowOpened

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        BridalPack bridalpack = new BridalPack();
        bridalpack.setVisible(true);
        Feedback fd=new Feedback();
        fd.setVisible(false);
        
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedbackresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedbackresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedbackresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedbackresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedbackresult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dot1;
    private javax.swing.JLabel dot2;
    private javax.swing.JLabel dot3;
    private javax.swing.JLabel dot4;
    private javax.swing.JLabel dot5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
