/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sally;

import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JYearChooser;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author ASUSI7
 */
public class BalanceSheet extends javax.swing.JFrame {

    /**
     * Creates new form BalanceSheet
     */
    write wr = new write();
    public BalanceSheet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        txt_2 = new javax.swing.JTextField();
        txt_4 = new javax.swing.JTextField();
        txt_3 = new javax.swing.JTextField();
        txt_5 = new javax.swing.JTextField();
        txt_6 = new javax.swing.JTextField();
        lbl_2 = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_7 = new javax.swing.JTextField();
        txt_8 = new javax.swing.JTextField();
        txt_9 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        txt_10 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_11 = new javax.swing.JTextField();
        txt_12 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbl_6 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl_7 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(847, 481));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 692));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(12, 173, 183));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Deepika Gunasekara Salon and Academy");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 330, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Balance Sheet");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("December 31 , ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 110, -1));
        jPanel2.add(lbl_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 70, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Excel");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 30, 90, 30));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1155, 99);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Liabilities");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(746, 130, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Assets");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(245, 130, 50, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Inventory");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 284, 61, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Current Assets");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 160, 89, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cash");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 191, 30, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Account Receivable");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 224, 119, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Prepaid Rent");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 257, 78, 17);

        jLabel15.setText("__________________");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(398, 321, 120, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Total current assets");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 347, 137, 17);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Long-term Assets");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(20, 390, 107, 17);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Stock Invesment");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(60, 428, 104, 17);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Insurance");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(60, 461, 60, 17);

        jLabel45.setText("______________________________________");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(290, 484, 251, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Total long-term assets");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 520, 155, 17);

        jLabel20.setText("__________________");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(410, 560, 120, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Tota Assets");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 590, 81, 17);

        txt_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_1);
        txt_1.setBounds(301, 188, 81, 23);

        txt_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_2);
        txt_2.setBounds(301, 221, 81, 23);

        txt_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_4);
        txt_4.setBounds(301, 287, 81, 23);

        txt_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_3);
        txt_3.setBounds(301, 254, 81, 23);

        txt_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_5);
        txt_5.setBounds(416, 425, 86, 23);

        txt_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_6);
        txt_6.setBounds(416, 458, 86, 23);

        lbl_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_2);
        lbl_2.setBounds(420, 510, 86, 23);

        lbl_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_1);
        lbl_1.setBounds(408, 347, 86, 23);

        lbl_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_3);
        lbl_3.setBounds(420, 580, 86, 25);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Current Liabilities");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(551, 168, 101, 17);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Account Payable");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(619, 199, 102, 17);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Accrued Taxes");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(619, 232, 90, 17);

        txt_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_7);
        txt_7.setBounds(876, 196, 81, 23);

        txt_8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_8);
        txt_8.setBounds(876, 229, 81, 23);

        txt_9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_9);
        txt_9.setBounds(876, 262, 81, 23);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Other Payable");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(619, 265, 86, 17);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Total Current Liabilities");
        jLabel30.setToolTipText("");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(563, 318, 158, 17);

        jLabel31.setText("__________________");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(858, 293, 120, 14);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Long-term Liabilities");
        jLabel32.setToolTipText("");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(584, 349, 119, 17);

        lbl_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_4);
        lbl_4.setBounds(880, 310, 80, 22);

        txt_10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_10ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_10);
        txt_10.setBounds(880, 350, 81, 23);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Owners Equity");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(694, 435, 117, 20);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Retained Earning");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(586, 499, 103, 17);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Capital Stock");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(586, 466, 79, 17);

        txt_11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_11);
        txt_11.setBounds(880, 460, 81, 30);

        txt_12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt_12);
        txt_12.setBounds(880, 500, 81, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Total Owner Equity");
        jLabel37.setToolTipText("");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(560, 560, 133, 17);

        jLabel38.setText("__________________");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(860, 580, 120, 14);

        lbl_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_6);
        lbl_6.setBounds(880, 560, 80, 22);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Total Liability and Owner Equity");
        jLabel43.setToolTipText("");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(560, 600, 218, 17);

        lbl_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_7);
        lbl_7.setBounds(880, 600, 80, 22);

        jLabel46.setText("__________________");
        jPanel1.add(jLabel46);
        jLabel46.setBounds(860, 530, 120, 14);

        jLabel47.setText("__________________");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(858, 375, 120, 14);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("Total Liabilites");
        jLabel48.setToolTipText("");
        jPanel1.add(jLabel48);
        jLabel48.setBounds(563, 395, 97, 17);

        lbl_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_5);
        lbl_5.setBounds(880, 400, 80, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(885, 105, 100, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Date :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 110, 40, 20);
        jPanel1.add(calendar);
        calendar.setBounds(60, 110, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_10ActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{      // TODO add your handling code here:
            int text1 = Integer.parseInt(txt_1.getText());
            int text2 = Integer.parseInt(txt_2.getText());
            int text3 = Integer.parseInt(txt_3.getText());
            int text4 = Integer.parseInt(txt_4.getText());
            int text5 = Integer.parseInt(txt_5.getText());
            int text6= Integer.parseInt(txt_6.getText());
            int text7= Integer.parseInt(txt_7.getText());
            int text8 = Integer.parseInt(txt_8.getText());
            int text9= Integer.parseInt(txt_9.getText());
            int text10= Integer.parseInt(txt_10.getText());
            int text11= Integer.parseInt(txt_11.getText());
            int text12= Integer.parseInt(txt_12.getText());
           
if(text1<0 || text2<0 ||text3<0 || text4<0 || text5<0 ||text6<0 || text7<0 || text8<0 ||text9<0 || text10<0 || text11<0 ||text12<0 )    
{

    JOptionPane.showMessageDialog(null, "Please enter valid data, minuse values not valid");

    } 

else if((txt_1.getText()).isEmpty() || (txt_2.getText()).isEmpty() ||(txt_3.getText()).isEmpty()||(txt_4.getText()).isEmpty()|| (txt_5.getText()).isEmpty()||(txt_6.getText()).isEmpty()||(txt_7.getText()).isEmpty() || (txt_8.getText()).isEmpty() ||(txt_9.getText()).isEmpty()||(txt_10.getText()).isEmpty()|| (txt_11.getText()).isEmpty()||(txt_12.getText()).isEmpty()){

        JOptionPane.showMessageDialog(null, "Please enter all Data");

}
else{
    
            LocalDateTime now = LocalDateTime.now();
            int year = now.getYear();
           int current_a = (text1+text2+text3+text4);
           lbl_1.setText(Integer.toString(current_a));
           int current_n = (text5+text6);
           lbl_2.setText(Integer.toString(current_n));
           int as =current_a+current_n;
           lbl_3.setText(Integer.toString(current_a+current_n));
           int liab = (text7+text8+text9);
           String C_liab = Integer.toString(liab);
           lbl_4.setText(C_liab);
           int li = (liab+text10);
           lbl_5.setText(Integer.toString(li));
           int equity=text11+text12;
           lbl_6.setText(Integer.toString(equity));
           int eq_li= li+equity;
           lbl_7.setText(Integer.toString(eq_li));
           
           if(eq_li==as){
           JOptionPane.showMessageDialog(null, "Balance sheet is balanced");
           
           }
           else
               JOptionPane.showMessageDialog(null, "Balance sheet is not balanced","Error",JOptionPane.ERROR_MESSAGE);
           
}

}
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        wr.getClass();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory((new File(System.getProperty("C:\\Users\\ASUSI7\\Desktop"))));        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_7;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_10;
    private javax.swing.JTextField txt_11;
    private javax.swing.JTextField txt_12;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_6;
    private javax.swing.JTextField txt_7;
    private javax.swing.JTextField txt_8;
    private javax.swing.JTextField txt_9;
    // End of variables declaration//GEN-END:variables
}
